# Math

(use the `print` function to print output to the screen)

### Simple arithmetic

In [1]:
print( 1 + 2 )     # addition
print( 1 - 5 )     # subtraction
print( 4 * 5 )     # multiplication
print( 4 / 5 )     # division
print( 3 ** 2 )    # exponent
print( 25 ** 0.5 ) # square root

3
-4
20
0.8
9
5.0


### Order of operations

- Python follows common order-of-operation rules (e.g. multiplication before addition)
- Use round brackets `(  )` to override order-of-operation rules

In [2]:
print( 1 + 2 * 3 )
print( 1 + (2 * 3) )
print( (1 + 2) * 3 )

7
7
9


# Variables

A variable is a symbol that contains data.

In [3]:
x = 1
y = 10
z = 10001
print( x )
print( y )
print( z )

1
10
10001


A single `print` statement can be used to display several variables.

In [4]:
print(x, y, z)

1 10 10001


The results of a variable calculation can be saved in another variable.

In [5]:
x = 1
y = 10
a = x + y
print( a )

11


### Dynamic typing  (type of variable)

- Python uses dynamic typing, which means that the variable type can be easily changed
- You can use the `type` command to check the variable type

In [6]:
x = 2
print( x, type(x) )

x = 2.7
print( x, type(x) )

x = "Hello!"
print( x, type(x) )

2 <class 'int'>
2.7 <class 'float'>
Hello! <class 'str'>


### Variable names

By convention:

- Variable names should contain only lower-case letters (abcde... NOT ABCDE...)
- Multi-name variables should be separated with underscores `_`
- Must start with a letter (not a number)

In [7]:
x0 = 1
x1 = 10
x2= 200
print(x0, x1, x2)

1 10 200


In [8]:
x99991180918019810981098 = 100

print( x99991180918019810981098 )

100


In [9]:
abc = 100
my_favorite_ice_cream = 10
ABC = 1000   # not an error, but not Python convention
myFavoriteIceCream = 200  # not an error, but not Python convention

print( abc )
print( ABC )
print( my_favorite_ice_cream )
print( myFavoriteIceCream )

100
1000
10
200


# Lists and tuples

- A list contains multiple variables in a sequence
- A tuple is a list that cannot be changed

In [10]:
x = [0, 5, 8]
y = (0, 5, 8)

print( x, type(x) )
print( y, type(y) )

[0, 5, 8] <class 'list'>
(0, 5, 8) <class 'tuple'>


In [11]:
x = [0, 5, 8]

print( x[0] )  # first element of x;  "zero indexing"
print( x[1] )  # second element of x
print( x[2] )  # third element of x

0
5
8


In [12]:
print( x[-1] )  # last element
print( x[-2] )  # second last element
print( x[-3] )  # third last element

8
5
0


List elements can be changed:

In [13]:
x    = [0, 10, 100]
x[0] = 2000
x[1] = -5

print( x )

[2000, -5, 100]


In [14]:
x = (0, 10, 100)
print( x[0] )

0


# Arrays

Creating arrays is usually done in Python using the NumPy package 

NumPy : Numerical Python

- A package is like a library, containing several programming tools like functions and variables.
- Packages must be accessed using the "import" command in Python



In [15]:
import numpy

x = numpy.array( [0, 5, 8] )

print( x, type(x) )   # n-dimensional array

[0 5 8] <class 'numpy.ndarray'>


In [16]:
print( x[0] )
print( x[1] )

0
5


In [17]:
print( x + 1 )
print( x - 1 )
print( x * 2 )
print( x / 2 )
print( x ** 2 )

[1 6 9]
[-1  4  7]
[ 0 10 16]
[0.  2.5 4. ]
[ 0 25 64]


In [18]:
import numpy as np

a = np.array( [0, 1, 5] )
b = np.array( [10, 10, 0] )

print( a + b )

[10 11  5]


In [19]:
c = [0, 1, 5]
d = [10, 10, 0]

print( c + d )

[0, 1, 5, 10, 10, 0]


# Functions

A function accepts input variables (called "input arguments"), performs calculations, and then returns output variables (called "output arguments") to the caller.

In [20]:
def my_function(x):
    y = x + 1
    return y

print( my_function(10) )

a = my_function(10)
print( a )

11
11


- `def` : define function
- `my_function` is the function name (should be named like variable names by convention)
- `x` : input argument
- `y` : output argument
- `return` indicates that the function is finished

In [21]:
def my_function(x, y):
    z = x + y
    q = 100
    return z, q

a,b = my_function(1, 2)
print(a, b)

3 100
